version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: as_all_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password