services:

  flask_app:
    build: ./src/voice_diary/
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      FLASK_ENV: production
      FLASK_APP: /app/app.py
    networks:
      - my_network

  mongodb:
    image: mongo:6.0
    container_name: as_all_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth
    networks:
      - my_network

networks:
  my_network:

volumes:
  mongodb_data:
